export const STATUS = {
  CRIADA: 'CRIADA',
  EM_TRANSITO: 'EM_TRANSITO',
  ENTREGUE: 'ENTREGUE',
  CANCELADA: 'CANCELADA',
};
 
export const TRANSICOES_VALIDAS = {
  [STATUS.CRIADA]: STATUS.EM_TRANSITO,
  [STATUS.EM_TRANSITO]: STATUS.ENTREGUE,
};
 
export const STATUS_FINAIS = [STATUS.ENTREGUE, STATUS.CANCELADA];
 